-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 18:47:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modeladoportafolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modeladoportafolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modeladoportafolio` DEFAULT CHARACTER SET utf8 ;
USE `modeladoportafolio` ;

-- -----------------------------------------------------
-- Table `modeladoportafolio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modeladoportafolio`.`persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `titulo` VARCHAR(60) NULL,
  `url_banner` VARCHAR(100) NULL,
  `url_imagen_persona` VARCHAR(100) NULL,
  `sobre_mi` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeladoportafolio`.`experiencia_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modeladoportafolio`.`experiencia_laboral` (
  `id` INT NOT NULL,
  `url_logo_empresa` VARCHAR(100) NULL,
  `nombre_empresa` VARCHAR(45) NULL,
  `puesto` VARCHAR(45) NULL,
  `trabajo_actual` TINYINT NULL,
  `inicio` DATE NULL,
  `finalizacion` DATE NULL,
  `descripcion` VARCHAR(200) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_experiencia_laboral_persona_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_laboral_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `modeladoportafolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeladoportafolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modeladoportafolio`.`educacion` (
  `id` INT NOT NULL,
  `url_foto_instituto` VARCHAR(100) NULL,
  `nombre_instituto` VARCHAR(60) NULL,
  `titulo` VARCHAR(60) NULL,
  `inicio` DATE NULL,
  `finalizacion` DATE NULL,
  `porcentaje_concluido` VARCHAR(45) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_educacion_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `modeladoportafolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeladoportafolio`.`certificados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modeladoportafolio`.`certificados` (
  `id` INT NOT NULL,
  `url_foto_institucion` VARCHAR(100) NULL,
  `nombre_institucion` VARCHAR(60) NULL,
  `certificado` VARCHAR(60) NULL,
  `anio` YEAR(4) NULL,
  `porcentaje_concluido` VARCHAR(45) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_certificados_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_certificados_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `modeladoportafolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeladoportafolio`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modeladoportafolio`.`proyectos` (
  `id` INT NOT NULL,
  `nombre_proyecto` VARCHAR(60) NULL,
  `fecha` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  `url_imagen_proyecto` VARCHAR(100) NULL,
  `url_proyecto` VARCHAR(100) NULL,
  `tecnologia` VARCHAR(45) NULL,
  `educacion_id` INT NOT NULL,
  `educacion_persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `educacion_id`, `educacion_persona_id`),
  INDEX `fk_proyectos_educacion1_idx` (`educacion_id` ASC, `educacion_persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_educacion1`
    FOREIGN KEY (`educacion_id` , `educacion_persona_id`)
    REFERENCES `modeladoportafolio`.`educacion` (`id` , `persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeladoportafolio`.`hard_soft_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modeladoportafolio`.`hard_soft_skills` (
  `id` INT NOT NULL,
  `tipo_habilidad` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) BINARY NULL,
  `grado_dominio` VARCHAR(45) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_hard_soft_skills_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_hard_soft_skills_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `modeladoportafolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeladoportafolio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modeladoportafolio`.`usuario` (
  `id` INT NOT NULL,
  `constrasenia` VARCHAR(10) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_usuario_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `modeladoportafolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeladoportafolio`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modeladoportafolio`.`contacto` (
  `id` INT NOT NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_contacto_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_contacto_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `modeladoportafolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modeladoportafolio`.`redes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modeladoportafolio`.`redes` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `url_enlace` VARCHAR(100) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`),
  INDEX `fk_redes_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_redes_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `modeladoportafolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
